### ISSUE TITLE
No more Field or Dialog to add external files in Media?

### ISSUE THREAD

**Issue by asso7i3n** [threadi/external-files-in-media-library#46]
Maybe since the last update, can't see anymore any area or field within the Media Library / media-new.php or anywhere.

**Comment by threadi** [comment]
The authorizations are probably incorrect. Have a look under Settings > External Files for Media Library > Permissions. There is a field where you can select the roles that should have access. Make sure that the roles you want are selected here and click on save - the permissions will then be reset and the selection field should be visible again immediately.

**Comment by threadi** [comment]
I think it's more of a bug that affects some people who update to 2.0.0. I'll open the issue again and take a look at it when I get the chance.
